// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("Encounter")));
bytes32 constant EncounterTableId = _tableId;

struct EncounterData {
  bool exists;
  bytes32 monster;
  uint256 catchAttempts;
}

library Encounter {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](3);
    _schema[0] = SchemaType.BOOL;
    _schema[1] = SchemaType.BYTES32;
    _schema[2] = SchemaType.UINT256;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](3);
    _fieldNames[0] = "exists";
    _fieldNames[1] = "monster";
    _fieldNames[2] = "catchAttempts";
    return ("Encounter", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get exists */
  function getExists(bytes32 player) internal view returns (bool exists) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (_toBool(uint8(Bytes.slice1(_blob, 0))));
  }

  /** Get exists (using the specified store) */
  function getExists(IStore _store, bytes32 player) internal view returns (bool exists) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (_toBool(uint8(Bytes.slice1(_blob, 0))));
  }

  /** Set exists */
  function setExists(bytes32 player, bool exists) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((exists)));
  }

  /** Set exists (using the specified store) */
  function setExists(IStore _store, bytes32 player, bool exists) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((exists)));
  }

  /** Get monster */
  function getMonster(bytes32 player) internal view returns (bytes32 monster) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (Bytes.slice32(_blob, 0));
  }

  /** Get monster (using the specified store) */
  function getMonster(IStore _store, bytes32 player) internal view returns (bytes32 monster) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (Bytes.slice32(_blob, 0));
  }

  /** Set monster */
  function setMonster(bytes32 player, bytes32 monster) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((monster)));
  }

  /** Set monster (using the specified store) */
  function setMonster(IStore _store, bytes32 player, bytes32 monster) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((monster)));
  }

  /** Get catchAttempts */
  function getCatchAttempts(bytes32 player) internal view returns (uint256 catchAttempts) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 2);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get catchAttempts (using the specified store) */
  function getCatchAttempts(IStore _store, bytes32 player) internal view returns (uint256 catchAttempts) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 2);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set catchAttempts */
  function setCatchAttempts(bytes32 player, uint256 catchAttempts) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    StoreSwitch.setField(_tableId, _keyTuple, 2, abi.encodePacked((catchAttempts)));
  }

  /** Set catchAttempts (using the specified store) */
  function setCatchAttempts(IStore _store, bytes32 player, uint256 catchAttempts) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    _store.setField(_tableId, _keyTuple, 2, abi.encodePacked((catchAttempts)));
  }

  /** Get the full data */
  function get(bytes32 player) internal view returns (EncounterData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, bytes32 player) internal view returns (EncounterData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(bytes32 player, bool exists, bytes32 monster, uint256 catchAttempts) internal {
    bytes memory _data = encode(exists, monster, catchAttempts);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(IStore _store, bytes32 player, bool exists, bytes32 monster, uint256 catchAttempts) internal {
    bytes memory _data = encode(exists, monster, catchAttempts);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(bytes32 player, EncounterData memory _table) internal {
    set(player, _table.exists, _table.monster, _table.catchAttempts);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, bytes32 player, EncounterData memory _table) internal {
    set(_store, player, _table.exists, _table.monster, _table.catchAttempts);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (EncounterData memory _table) {
    _table.exists = (_toBool(uint8(Bytes.slice1(_blob, 0))));

    _table.monster = (Bytes.slice32(_blob, 1));

    _table.catchAttempts = (uint256(Bytes.slice32(_blob, 33)));
  }

  /** Tightly pack full data using this table's schema */
  function encode(bool exists, bytes32 monster, uint256 catchAttempts) internal view returns (bytes memory) {
    return abi.encodePacked(exists, monster, catchAttempts);
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(bytes32 player) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 player) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 player) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((player));

    _store.deleteRecord(_tableId, _keyTuple);
  }
}

function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
