// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */
enum Direction {
  North,
  East,
  South,
  West
}

enum TerrainType {
  None,
  TallGrass,
  Boulder
}
