// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Encounter, EncounterData } from "./tables/Encounter.sol";
import { EncounterTrigger } from "./tables/EncounterTrigger.sol";
import { Encounterable } from "./tables/Encounterable.sol";
import { MapConfig } from "./tables/MapConfig.sol";
import { MonsterCatchAttempt } from "./tables/MonsterCatchAttempt.sol";
import { Monster } from "./tables/Monster.sol";
import { Movable } from "./tables/Movable.sol";
import { Obstruction } from "./tables/Obstruction.sol";
import { OwnedBy } from "./tables/OwnedBy.sol";
import { Player } from "./tables/Player.sol";
import { Position } from "./tables/Position.sol";
