// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum MonsterType {
  None,
  Eagle,
  Rat,
  Caterpillar
}

enum TerrainType {
  None,
  TallGrass,
  Boulder
}
